[package]
name = "hab-shell"
version = "0.1.0"
authors = ["Danil Guskov <d.guskov@corp.mail.ru>"]

[dependencies]
clap = "=2.31.2"
dotenv = "*"
tempfile = "*"
habitat_core = { git = "https://github.com/habitat-sh/core.git" }