[package]
name = "hab-shell"
version = "0.1.13"
authors = ["Danil Guskov <guskovd86@mail.ru>"]

[dependencies]
clap = "=2.31.2"
dotenv = "*"
tempfile = "*"
dirs = "*"
habitat_core = { git = "https://github.com/habitat-sh/core.git" }
rust-ini = "0.13"
